import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import {
  catalogRevision,
  formatJson,
  readJson,
  repositoryRoot,
  validateCatalog,
} from "./catalog-lib.mjs";

const checkOnly = process.argv.includes("--check");
const catalogPath = path.join(repositoryRoot, "catalog/catalog.json");
const catalog = await validateCatalog(await readJson(catalogPath));
const revision = await catalogRevision(catalog);

const rootPackage = await readJson(path.join(repositoryRoot, "package.json"));
const npmPackage = await readJson(
  path.join(repositoryRoot, "packages/theme/package.json"),
);
const cargoManifest = await readFile(path.join(repositoryRoot, "Cargo.toml"), "utf8");
const cargoVersion = cargoManifest.match(
  /\[workspace\.package\][\s\S]*?\nversion = "([^"]+)"/,
)?.[1];

for (const [name, version] of [
  ["workspace npm package", rootPackage.version],
  ["@stack-sh/theme", npmPackage.version],
  ["stack-theme", cargoVersion],
]) {
  if (version !== catalog.catalogVersion) {
    throw new Error(
      `${name} version ${version ?? "<missing>"} does not match catalog ${catalog.catalogVersion}`,
    );
  }
}

const catalogJson = formatJson(catalog);
const metadata = {
  catalogVersion: catalog.catalogVersion,
  catalogRevision: revision,
};
const metadataJson = formatJson(metadata);
const licenseText = await readFile(path.join(repositoryRoot, "LICENSE"), "utf8");
const schemaText = await readFile(
  path.join(repositoryRoot, "schemas/catalog.schema.json"),
  "utf8",
);
const assetEntries = [];
const licensePaths = new Set(["LICENSE"]);
for (const metrics of catalog.fontMetrics) {
  licensePaths.add(metrics.provenance.licenseFile);
}
for (const theme of catalog.themes) {
  for (const icon of theme.icons) {
    if (!icon.asset.path.startsWith("assets/")) {
      throw new Error(
        `source catalog asset must be under assets/: ${icon.asset.path}`,
      );
    }
    assetEntries.push([
      icon.asset.path,
      await readFile(path.join(repositoryRoot, icon.asset.path), "utf8"),
    ]);
    licensePaths.add(icon.asset.provenance.licenseFile);
  }
}
assetEntries.sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0));

const assetObject = Object.fromEntries(assetEntries);
const generatedJavaScript = `// Generated by scripts/generate.mjs. Do not edit.\nconst catalogData = ${JSON.stringify(catalog, null, 2)};\nconst iconAssetsData = ${JSON.stringify(assetObject, null, 2)};\n\nfunction deepFreeze(value) {\n  Object.freeze(value);\n  for (const child of Object.values(value)) {\n    if (child !== null && typeof child === "object" && !Object.isFrozen(child)) {\n      deepFreeze(child);\n    }\n  }\n  return value;\n}\n\nexport const catalog = deepFreeze(catalogData);\nexport const catalogVersion = ${JSON.stringify(catalog.catalogVersion)};\nexport const catalogRevision = ${JSON.stringify(revision)};\nexport const iconAssets = deepFreeze(iconAssetsData);\nexport function iconSvg(assetPath) {\n  return iconAssets[assetPath];\n}\n`;
const rustAssetArms = assetEntries
  .map(
    ([assetPath]) =>
      `        ${JSON.stringify(assetPath)} => Some(include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/${assetPath}"))),`,
  )
  .join("\n");
const rustAssetFunction =
  rustAssetArms === ""
    ? "pub fn icon_svg(_asset_path: &str) -> Option<&'static str> {\n    None\n}"
    : `pub fn icon_svg(asset_path: &str) -> Option<&'static str> {\n    match asset_path {\n${rustAssetArms}\n        _ => None,\n    }\n}`;
const generatedRust = `// Generated by scripts/generate.mjs. Do not edit.\npub const CATALOG_VERSION: &str = ${JSON.stringify(catalog.catalogVersion)};\npub const CATALOG_REVISION: &str = ${JSON.stringify(revision)};\n\n${rustAssetFunction}\n`;

const artifacts = new Map([
  ["crates/stack-theme/LICENSE", licenseText],
  ["crates/stack-theme/schema/catalog.schema.json", schemaText],
  ["crates/stack-theme/src/generated/catalog.json", catalogJson],
  ["crates/stack-theme/src/generated/metadata.rs", generatedRust],
  ["packages/theme/LICENSE", licenseText],
  ["packages/theme/schema/catalog.schema.json", schemaText],
  ["packages/theme/catalog.json", catalogJson],
  ["packages/theme/catalog-metadata.json", metadataJson],
  ["packages/theme/catalog.generated.js", generatedJavaScript],
]);

for (const [assetPath, svg] of assetEntries) {
  artifacts.set(`crates/stack-theme/${assetPath}`, svg);
  artifacts.set(`packages/theme/${assetPath}`, svg);
}
for (const licensePath of [...licensePaths].sort()) {
  const contents = await readFile(path.join(repositoryRoot, licensePath), "utf8");
  artifacts.set(`crates/stack-theme/${licensePath}`, contents);
  artifacts.set(`packages/theme/${licensePath}`, contents);
}

for (const [relativePath, contents] of artifacts) {
  const outputPath = path.join(repositoryRoot, relativePath);
  if (checkOnly) {
    let actual;
    try {
      actual = await readFile(outputPath, "utf8");
    } catch {
      throw new Error(`${relativePath} is missing; run npm run generate`);
    }
    if (actual !== contents) {
      throw new Error(`${relativePath} is stale; run npm run generate`);
    }
  } else {
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, contents);
  }
}

console.log(
  `${checkOnly ? "verified" : "generated"} catalog ${catalog.catalogVersion} (${revision})`,
);
